In [2]:
import numpy as num
import matplotlib.pyplot as plt
from matplotlib import use
import pylab as lab
from scipy import constants
from matplotlib import rcParams
import os

from scipy.optimize import curve_fit

os.chdir("/home/hbhattar/afs/Hemanta/metals/pythonScripts/function")

import FDEAM as feam

os.chdir("/home/hbhattar/afs/Hemanta/metals/pythonScripts/")

In [7]:
frames=10
rawData=feam.DumpExtractor("../TestSurf/4Atom.dump",10,4,0)
[vxd,vyd,vzd]=rawData["velocity"]
[xd,yd,zd]=rawData["position"]
[cd,wd]=rawData["chargeQV"]
[exd,eyd,ezd]=rawData["electricField"]
       

In [13]:
ezd

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
frames=10
rawData=feam.DumpExtractor("../TestSurf/4AtomDSFD.dump",10,4,0)
[vxs,vys,vzs]=rawData["velocity"]
[xs,ys,zs]=rawData["position"]
[cs,ws]=rawData["chargeQV"]
[exs,eys,ezs]=rawData["electricField"]

In [14]:
ezd

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
file=open("../ZhouCrystalCalculations/Ag.omd")

In [21]:
lines=file.readlines()

In [38]:
import re
for line in lines:
    word=line.split()
    if "Hmat:" in word:
        print(word)
        print(word[2],word[8],word[14])
        match_number = re.compile('-?\ *[0-9]+\.?[0-9]*(?:[Ee]\ *[-+]?\ *[0-9]+)?')
        Lx=[float(x) for x in re.findall(match_number,word[2])]
        Ly=[float(y) for y in re.findall(match_number,word[8])]
        Lz=[float(z) for z in re.findall(match_number,word[14])]

['Hmat:', '{{', '40.027602,', '0.000000,', '0.000000', '},', '{', '0.000000,', '23.109947,', '0.000000', '},', '{', '0.000000,', '0.000000,', '28.303789', '}}']
40.027602, 23.109947, 28.303789


In [78]:
e1=num.random.rand(9).reshape(3,3)

In [79]:
def f(e):
    return e+.5*num.matmul(e,e)

In [80]:
eta=f(e1)

In [84]:
e=num.zeros(9).reshape(3,3)
for var in range(100000):
    e=eta-.5*num.matmul(e,e)

In [85]:
e-e1

array([[-0.25685529, -0.52342052, -0.45994591],
       [-0.13858938, -0.28241788, -0.24816938],
       [-0.19741031, -0.40228335, -0.3534989 ]])